// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP508gU3EX6pR4GTyz2BBltxSedO1ToVs',
    appId: '1:144240869927:web:b0bfdfae3e3e3abe8e0402',
    messagingSenderId: '144240869927',
    projectId: 'aktalaa-jarnama-42360',
    authDomain: 'aktalaa-jarnama-42360.firebaseapp.com',
    storageBucket: 'aktalaa-jarnama-42360.appspot.com',
    measurementId: 'G-9ZM614S129',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL8PWc36ShnA8YS8U_ihYy4kjxs3VkJ2Y',
    appId: '1:144240869927:android:5301a1a657e93f0e8e0402',
    messagingSenderId: '144240869927',
    projectId: 'aktalaa-jarnama-42360',
    storageBucket: 'aktalaa-jarnama-42360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV7AT-uLOOVRTWEmn7gtY12r8ekMh9Cds',
    appId: '1:144240869927:ios:ac0c31a61f82bb888e0402',
    messagingSenderId: '144240869927',
    projectId: 'aktalaa-jarnama-42360',
    storageBucket: 'aktalaa-jarnama-42360.appspot.com',
    iosClientId: '144240869927-3kuhisu64svenlt1ofqqkiii0eb03kk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.aktalaaJarnama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV7AT-uLOOVRTWEmn7gtY12r8ekMh9Cds',
    appId: '1:144240869927:ios:a74fb01386bd0f068e0402',
    messagingSenderId: '144240869927',
    projectId: 'aktalaa-jarnama-42360',
    storageBucket: 'aktalaa-jarnama-42360.appspot.com',
    iosClientId: '144240869927-g1gikp0lnlk93oainggh363ke4b328ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.aktalaaJarnama.RunnerTests',
  );
}
